In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([0,0,0])
c = np.vstack((a,b))

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [13]:
d = np.vstack((a,b,c))

In [15]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [17]:
(a,b)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([0, 0, 0]))

In [19]:
x = (1,2,3)

In [21]:
x

(1, 2, 3)

In [28]:
print(type(x))

<class 'tuple'>
